### ISSUE TITLE
Azure deployment fails same place each attempt

### ISSUE THREAD

**Issue by stuckbear** [OfficeDev/microsoft-teams-apps-newemployeeonboarding#10]
"statusCode": "Conflict",
      "statusMessage": {
        "status": "Failed",
        "error": {
          "code": "ResourceDeploymentFailure",
          "message": "The resource operation completed with terminal provisioning state 'Failed'."
      }
      },
      "targetResource": {
        "id": "/subscriptions/subid/resourceGroups/Teams-App-Templates-POC/providers/Microsoft.Web/sites/NEO/sourcecontrols/web",
        "resourceType": "Microsoft.Web/sites/sourcecontrols",
        "resourceName": "NEO/web"

**Comment by eliezerbnu** [comment]
Hello,

I did the deployment of the application successfully.
The problem in deploy is due to lack of computational resource for the app build.
After you complete deploy, ignore error and go to the web app, change the service plan from S2 to S3 in Scale Up (App Service Plan).

![neo-sp](https://user-images.githubusercontent.com/53222753/109935360-447a0a80-7cac-11eb-8f68-ae9cbc2e0380.jpg)


Go back to the central azure web application deployment tab, click Reimplanar/Sync, and wait until you complete the process successfully.
![neo-success](https://user-images.githubusercontent.com/53222753/109935402-5196f980-7cac-11eb-851e-9c6b9bc0f318.jpg)


Good Luck for all.
